version: '3.4'

services:
  pedidoapi:
    image: ${DOCKER_REGISTRY}pedidoapi
    build:
      context: .
      dockerfile: Pedido.API/Dockerfile
  angular:
    image: ${DOCKER_REGISTRY}angular
    build:
      context: .
      dockerfile: pedido-ui/Dockerfile